language: node_js
node_js: stable
sudo: required
cache:
  directories:
    - $(npm config get prefix)
    - bower_components
branches:
  only:
    - master
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
before_script:
<<<<<<< HEAD
  - npm install -g polylint web-component-tester
  - polylint
script:
  - xvfb-run wct --module-resolution=node --npm
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --module-resolution=node --npm -s ''default''; fi'

=======
  - npm install -g polymer-cli
  - polymer install --variants
script:
  - xvfb-run polymer test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default'; fi
notifications:
  email: change
>>>>>>> 2ce55b71532b3e392f228a2b765526248532babd
