language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g bower polymer-cli
  - bower install
  - polymer lint
script:
  - xvfb-run polymer test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default'; fi
